name: client
description: Urban Taxi

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^2.2.1
  outline_material_icons: ^0.1.1
  google_maps_flutter: ^0.5.28+1
  flutter_svg: ^0.19.0
  geolocator: ^5.3.1
  snapping_sheet: ^2.0.1
  flutter_statusbarcolor: ^0.2.3
  bloc: ^6.0.1
  fade: ^1.0.0
  dio: ^3.0.9
  http: ^0.12.0+4
  shared_preferences: ^0.5.10
  device_info: ^0.4.2+7
  get_ip: ^0.4.0
  simple_timer: ^1.0.1
  location: ^3.2.4
  group_radio_button: ^1.0.1
  rxdart: ^0.24.1
  date_field: ^0.3.0
  after_init: ^0.1.2
  intl: ^0.16.1
  socket_io_client: ^0.9.11
  image_picker: ^0.6.7+14
  image_cropper: ^1.2.3
  http_parser: ^3.1.4
  url_launcher: ^5.5.3
  back_button_interceptor: ^4.3.1
  flutter_datetime_picker: ^1.4.0
  flutter_launcher_icons: ^0.8.0
  country_pickers: ^1.3.0
  onesignal_flutter: ^2.3.0
  sign_in_with_apple: ^2.5.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_facebook_login: ^3.0.0
  smooth_star_rating: ^1.1.1
  google_sign_in: ^4.5.6
  change_app_package_name: ^0.1.2
  share: ^0.6.5+2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/urban-icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/payments/
    - assets/rides/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
    - family: Lato-light
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-LightItalic.ttf
          style: italic
    - family: Lato-thin
      fonts:
        - asset: assets/fonts/Lato-Thin.ttf
        - asset: assets/fonts/Lato-ThinItalic.ttf
          style: italic
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
